plugins {
  id "java-library"
  id "maven-publish"
  alias(libs.plugins.fabric.loom) apply false
  alias(libs.plugins.neogradle) apply false
  alias(libs.plugins.modstitch.multiloader)
  alias(libs.plugins.modstitch.manifests)
  alias(libs.plugins.modstitch.modrepos)
  alias(libs.plugins.modstitch.accessx)
}

version = project.mod_version + "+" + project.minecraft_version
group = project.maven_group

final var canonicalAW = layout.projectDirectory.file("fantasy.accesswidener")

// Loom does everything at configuration time which means accessx cannot be used
// to source comptime access wideners
loom.accessWidenerPath = canonicalAW


final var fabricAWTask = accessx.convert("fabric", sourceSets.fabric.name) {
  inputFiles.from(canonicalAW)
  outputFormat = accessx.AW_V1
}
// modstitch-accessx: converts the access widener into an access transformer and includes it in resources
final var neoforgeAWTask = accessx.convert("neoforge", sourceSets.neoforge.name) {
  inputFiles.from(canonicalAW)
  outputFormat = accessx.AT
}
// access transformers must be sourced BEFORE `neoforgeImplementation(libs.neoforge)`
accessTransformers.files.from(neoforgeAWTask.flatMap { it.outputFile })
// NeoGradle bug: https://github.com/neoforged/NeoGradle/issues/318
tasks.named { it in ["neoFormTransformSource", "applyAccessTransformer"] }.configureEach {
  dependsOn(neoforgeAWTask)
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(25)
  }
}

base {
  archivesName = project.archives_base_name
}

sourceSets {
  testmod {
    compileClasspath += main.compileClasspath
    runtimeClasspath += main.runtimeClasspath
  }
}

loom {
  runs {
    testmodClient {
      client()
      name = "Testmod Client"
      source sourceSets.testmod
    }
    testmodServer {
      server()
      name = "Testmod Server"
      source sourceSets.testmod
    }
  }

//  accessWidenerPath = file("src/main/resources/fantasy.accesswidener")
}

repositories {
  maven { url = "https://maven.gegy.dev/" }
  maven { url = "https://maven.nucleoid.xyz/" }
  maven { url = "https://maven.terraformersmc.com/releases" }
}

dependencies {
//  minecraft "com.mojang:minecraft:${project.minecraft_version}"
//  implementation "net.fabricmc:fabric-loader:${project.loader_version}"
//
//  implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
//
//  testmodImplementation sourceSets.main.output

  minecraft(libs.minecraft)
  fabricLoader(libs.fabric.loader)
  fabricImplementation(platform(libs.fabric.api.bom))
  fabricRuntimeOnly(libs.fabric.api)
  fabricRuntimeOnly(libs.mod.menu)
  fabricImplementation(libs.fabric.api)
  neoforgeImplementation(libs.neoforge)

}

processResources {
  inputs.property "version", project.version

  filesMatching("fabric.mod.json") {
    expand "version": project.version
  }
}

tasks.withType(JavaCompile).configureEach {
  it.options.encoding = "UTF-8"
  it.options.release = 25
}

java {
  withSourcesJar()

  sourceCompatibility = JavaVersion.VERSION_25
  targetCompatibility = JavaVersion.VERSION_25
}

jar {
  from "LICENSE"
}

final var minecraftConstraint = "[26.1,26.2)"
final var supportedMinecraftVersions = manifests.minecraftReleasesMatching(minecraftConstraint)

// modstitch-manifests: programmatic fabric.mod.json and neoforge.mods.toml generation
manifests {
  // most properties are common between mod loader manifests so only need to be defined once
  // this object can be brought out of the `manifests {}` block for reference in other parts of the
  // buildscript.
  // you can also source *all* of these properties through Providers i.e., providers.gradleProperty("prop")
  final var common = manifests.manifest {
    modId = "fantasy"
    version = project.version.toString()
    displayName = "Fantasy"
    description = "Fantasy is a library that allows for dimensions to be created and destroyed at runtime on the server."
    authors = ["Nucleoid Contributors", "Jab125"]
    sourcesUrl = "https://github.com/Minimega-Project/fantasy"
    licenses = ["MIT"]
    iconPath = "icon.png"

    // maven-like version ranges are automatically converted to the target platform's
    // version range format, i.e., fabric's ~26.1
    dependency("minecraft", REQUIRED, minecraftConstraint)

    mixin("fantasy.mixins.json")
  }

  // Generates the defined manifests into source set's resources
  fabricModJson(sourceSets.fabric) {
    from(common)

    entrypoint("main", "xyz.nucleoid.fantasy.fabric.FantasyFabric::init")

    mixin("fantasy.fabric.mixins.json")

    accessWidener(fabricAWTask)
    customData = [modmenu: [badges: ["library"]]]
    dependency("fabric-api", DEPENDS, libs.versions.fabric.api.get())
    dependency("java", DEPENDS, "[25,)")
    dependency("fabricloader", DEPENDS, libs.versions.fabric.loader.get())
  }
  neoForgeModsToml(sourceSets.neoforge) {
    from(common)

    mixin("fantasy.neoforge.mixins.json")

    accessTransformer(neoforgeAWTask)
  }
}

publishing {
  publications {
    mavenJava(MavenPublication) {
      artifact(tasks.universalJar)
      artifact(tasks.universalSourcesJar)
    }
  }

  repositories {
    def env = System.getenv()
    if (env.MAVEN_URL) {
      maven {
        credentials {
          username env.MAVEN_USERNAME
          password env.MAVEN_PASSWORD
        }
        url env.MAVEN_URL
      }
    } else {
      mavenLocal()
    }
  }
}
